name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
     REPO_URL:
      description: 'REPO URL'
      default: ''
      required: true  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.REPO_URL }} 

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build APK
      run: |
        ./gradlew assembleRelease
        mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/pif.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repository: ${{ env.REPO_URL }}
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload APK to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/pif.apk
        asset_name: pif.apk
        asset_content_type: application/vnd.android.package-archive
